### ISSUE TITLE
Example in documentation re: colour variable

### ISSUE THREAD

**Issue by JoeMurray** [babu-cat/mosaico-templating-tool#1]
Thanks for putting this together. I'm evaluating whether this will be useful for a client with two languages.

The example is very helpful, and the instructions are very clear for the most part. However, I'm still a little confused by the example and would be happy to submit a PR to clarify it if I understood it better.

1. In the example, there are three vars, right? brand_color, name, text. 

2. CiviCRM should be used to generate the name somehow, rather than having it generated once per template, if I understand correctly. However, I'm used to seeing  {contact.display_name} as a token - why are you using {{ name }} rather than a token like {contact.display_name} ? 

3. I love the config directory and file tree - it's very clear. But from the example text I'm not sure why there are not six files after the script is run, like this:

> dist
>   └── template1
>       ├── color1
>       │    └── template1-en-color1.html
>       │    └── template1-es-color1.htm
>       ├── color2
>       │    ├── template1-en-color2.html
>       │    └── template1-es-color2.html
>       └── color3
>            └── template1-en-color3.html
>            └── template1-es-color3.html
> 

I think in section 3 you start explaining how to override the languages to be generated by adding an array in the relevant vars file. So in order to make the example work, am I right in supposing that the following needs to be added to the config/template1/vars/color1.php and config/template1/vars/color3.php files:

> ...
>     'langs' => array(
>         'en'
>     ),
> ...

**Comment by francescbassas** [comment]
Thanks @JoeMurray for the comments. I will try to resolve your doubts.

1) There are three vars but with different purposes. "name" and "text" are text strings for localization. brand_color is for template versions (for example if you want to use the same template for various clients you could define vars like logo, brand_color, urls to get one template for each client.

2) Use of {{name}} is purelly illustrative to explain tool function. Surely the sample is not the right one.

3) There may be inconsistencies in the documentation. If in config/template1/vars/color3.php there is a 'langs' => array('en'), then only one template template1-en-color3.php it should be generated.

**Comment by francescbassas** [comment]
I'm pending to try this tool with a HTMML mosaico template https://github.com/voidlabs/htmml. Maybe make sense to integrate this tool with HTMML.

**Comment by JoeMurray** [comment]
Thanks again for this tool. Looking forward to other work you may do to support multilingual mailings from Civi. I'll likely post questions if needed.
