### ISSUE TITLE
Using the output?

### ISSUE THREAD

**Issue by JoeMurray** [babu-cat/mosaico-templating-tool#2]
I'm wondering if the documentation could have an additional section explaining what to do after the script is run in order to make use of the templates generated. 

1. Do they need to be cut and pasted into CiviCRM templates?

2. When mailing with CiviCRM, how should one configure the email and recipients? For example, should one create a mailing group based on their language preference (and color choice, to go with example in docs), and then create one mailing for each generated template?
![2018-10-18_11-08-04](https://user-images.githubusercontent.com/300943/47164790-aea1d880-d2c6-11e8-8063-3c081c690417.png)

3. When doing a scheduled reminder, if one specified as the Communication Language Follow recipient preferred language, would it somehow pick up templates based on language??
![2018-10-18_11-07-28](https://user-images.githubusercontent.com/300943/47164837-c6795c80-d2c6-11e8-9535-9cba1a3f01c9.png)
Or to make use of this script from you, should one similarly create one reminder for each template produced by the script, and use the Limit or Add Recipients to exclude people based on the language preference (and whether I want to send them one color or another).

Again, if you can set me straight, then I'll update the docs with PRs.

Thanks!!

**Comment by francescbassas** [comment]
1) The initial purpose of this tool is to keep it simple the mantainment of the mosaico templates in multiple languages and in second term make theme brand configurable. Once templates are generated they should be put on they own folder with edres and img directorys in the CiviCRM mosaico template directory.

2) When mailing we do one mail for language with its corresponding template. We have groups segmenting per language preference. You can see more how we work here https://chat.civicrm.org/civicrm/pl/qxbri8w1a7db98fynozfbo9zkr

3) We do not use mosaico templates with system message templates or scheduled reminders. It is possible? I think isn't it.

**Comment by JoeMurray** [comment]
Thanks!
